hack4impact-uiuc/h4i-recruitment

- backend/index.js
> error wrapping async endpoints

- README.md
- backend/.gitignore
- backend/src/index.js
- backend/src/models/candidate.js
- backend/src/parseSheet.js
- frontend/src/components/candidateBox.js
- frontend/src/components/candidateCard.js
- frontend/src/pages/index.js
- frontend/src/utils/api.js
Resolves #23 
Bugs:
- Cards don't render correctly when under 3 candidates displayed
- Initializing statuses to "pending" endpoint doesn't work, commented in code. I had to go through and manually assign each one to pending.
> Can filter by status and assign status to Candidates

- backend/src/candidates.js
- backend/src/index.js
- backend/src/matchCandidates.js
- frontend/src/utils/api.js
Resolves #45 
Endpoints are now split into different files for better design and organization. Original functionality maintained.
> Grouped endpoints and separated into different files

- backend/README.md
> fixed backend instructions

- README.md
> Added CircleCI status icon

- backend/src/models/candidate.js
- backend/src/models/match.js
> Store data to support facemash algorithm

- backend/.gitignore
- backend/package.json
- backend/src/app.js
- backend/yarn.lock
Resolves #40 
Logs are now written to `backend/logs/h4i-recruitment.log` and to STDOUT
> #40 add logger to backend

- frontend/src/components/candidateCard.js
- frontend/src/components/candidateList.js
- frontend/src/components/filterComponent.js
- frontend/src/components/nav.js
- frontend/src/pages/candidate.js
- frontend/src/pages/facemash.js
- frontend/src/pages/index.js
- frontend/src/pages/interview.js
- frontend/src/static/style.css
> add navbar + a little cleanup

- frontend/package.json
- frontend/src/pages/_app.js
- frontend/src/pages/candidate.js
- frontend/src/pages/facemash.js
- frontend/src/pages/index.js
- frontend/yarn.lock
> Upgrade to Next 6 and Next-redux-wrapper 2.x.x

- frontend/src/components/candidateBox.js
- frontend/src/pages/index.js
- frontend/src/static/style.css
> no issue: tiny style patches + resume link patch

- backend/src/api/candidates.js
- backend/src/models/candidate.js
- backend/src/models/comment.js
- backend/src/models/index.js
- backend/tests/candidates.test.js
- frontend/src/components/addCommentsModal.js
- frontend/src/components/commentBox.js
- frontend/src/components/nav.js
- frontend/src/pages/candidate.js
- frontend/src/static/style.css
- frontend/src/utils/api.js
Resolves #99
user will not be "unrecorded user" until keys are in use
> Ref #99 add comment ability to candidates

- frontend/src/pages/interview.js
- frontend/src/pages/login.js
- frontend/src/pages/past-interviews.js
- frontend/src/utils/api.js
Resolves #116 
uses sessionStorage instead of localStorage
> Resolves #116 - changed key storage to sessionStorage

- backend/tests/interview.test.js
Resolves #119
It's all green baby
> Resolves #119 fixes interview tests

- frontend/src/components/candidateBox.js
- frontend/src/components/candidateDropdown.js
- frontend/src/components/errorMessage.js
- frontend/src/components/nav.js
- frontend/src/pages/_app.js
- frontend/src/pages/candidate.js
- frontend/src/pages/facemash.js
- frontend/src/pages/index.js
- frontend/src/pages/interview.js
- frontend/src/static/style.css
> Resolves #130 created general error Component + fixed error Boundaries

- backend/src/api/matchCandidates.js
- backend/src/models/match.js
- backend/tests/matches.test.js
> saves user who made match

- backend/docs/interview_schema.md
- backend/src/api/interview.js
- backend/src/models/interview.js
- frontend/src/components/candidateDropdown.js
- frontend/src/components/interviewCategory.js
- frontend/src/pages/interview.js
- frontend/src/utils/api.js
- frontend/src/utils/enums.js
Resolves #<92>
Categories in interview
Category can be viewed in interview modal done by Megha
> Add Categories to interview

- backend/src/api/interview.js
- frontend/src/components/candidateBox.js
- frontend/src/utils/api.js
Resolves #92 Resolves #113 
Interview Summary in Candidate Page
> Candidate interview info

- backend/src/api/interview.js
- frontend/src/actions/actionCreators.js
- frontend/src/components/candidateBox.js
- frontend/src/components/interviewCard.js
- frontend/src/components/interviewCategory.js
- frontend/src/pages/interview.js
- frontend/src/static/style.css
> styled and update interview page

- frontend/src/pages/index.js
Resolves #131
If there aren't any candidates case you aren't logged in, it just shows the query panel with no candidates
> error message 

- backend/src/api/interview.js
- backend/src/middleware/auth.js
- backend/src/models/interview.js
- backend/tests/interview.test.js
- frontend/src/components/candidateBox.js
- frontend/src/components/nav.js
- frontend/src/pages/interview.js
- frontend/src/static/style.css
> navbar shows user's name when logged in. fixed interview overallScore

- frontend/src/actions/actionCreators.js
- frontend/src/actions/index.js
- frontend/src/components/candidateBox.js
- frontend/src/components/facemashProfile.js
- frontend/src/pages/interview.js
- frontend/src/pages/interviewportal.js
- frontend/src/utils/api.js
Resolves #152 
Added tiny blurb on interview tips along with links to interview guides.
Also turned off submit button if general notes isn't provided.
And made modal to double check if the interviewer wants to submit their notes:
> Resolves #152 added candidate profile to interview page

- backend/src/api/candidates.js
- frontend/src/components/candidateBox.js
- frontend/src/components/candidateCard.js
- frontend/src/components/candidateLinks.js
- frontend/src/components/candidateLinksBadge.js
- frontend/src/components/facemashProfile.js
- frontend/src/pages/index.js
- frontend/src/pages/table.js
Resolves #156
Behavior is the same
> Resolves #156 splits candidate links into a separate component

- frontend/src/components/nav.js
- frontend/src/pages/dashboard.js
- frontend/src/pages/index.js
- frontend/src/static/style.css
> Resolves #84 created login page as the index.js

- backend/src/api/matchCandidates.js
- backend/tests/matches.test.js
> Rejected candidates don't get facemashed

- frontend/src/pages/index.js
- frontend/src/pages/interview.js
- frontend/src/static/style.css
no issue
also removed interview tips
> added spinner for login screen

- backend/src/api/candidates.js
- backend/src/models/candidate.js
- backend/src/routes.js
- backend/src/utils/enums.js
- backend/src/utils/gitScraper.js
- backend/src/utils/parseSheet.js
- frontend/src/components/candidateBox.js
- frontend/src/components/facemashProfile.js
- frontend/src/pages/dashboard.js
- frontend/src/static/style.css
- frontend/src/utils/enums.js
> modified parse sheet - haven't tested yet

- frontend/src/utils/enums.js
> enums fixed

- frontend/src/components/candidateBox.js
- frontend/src/components/interviewSectionCard.js
- frontend/src/pages/interview.js
- frontend/src/static/style.css
- frontend/src/utils/enums.js
> updated interview page

- backend/src/utils/parseSheet.js
- backend/tests/matches.test.js
- frontend/src/components/candidateBox.js
- frontend/src/components/candidateCard.js
- frontend/src/pages/index.js
- frontend/src/pages/interview.js
- frontend/src/pages/table.js
Resolves #170 
it's actually in production rn
Also commented out broken facemash test, which will be fixed #174
> Ref #170 added emails/id to candidate page + other clean up

- backend/tests/artifacts/test-keys.json
- frontend/src/components/nav.js
- frontend/src/pages/dashboard.js
- frontend/src/pages/interview.js
- frontend/src/pages/table.js
- frontend/src/reducers/initialState.js
- frontend/src/utils/core.js
no issue
- Hours don't show up by default in the dashboard making it simplier
- clicking the logo in the navbar goes to /dashboard if a user is logged in
- added back search bar
- facemash elo and matches are now reversed so the top score shows up first
> cleaned up some user flows

- backend/src/api/interview.js
- backend/tests/interview.test.js
- frontend/src/components/candidateBox.js
- frontend/src/pages/interviewlist.js
- frontend/src/pages/interviewportal.js
- frontend/src/static/style.css
- frontend/src/utils/api.js
- added interviewer name to candidate box
Resolves #177 Resolves #186
It's kinda ugly but whatever...
> Resolves #177, #186 added all interview page

- .circleci/config.yml
- backend/docs/interview_schema.md
- backend/package.json
- backend/src/api/candidates.js
- backend/src/api/matchCandidates.js
- backend/src/routes.js
- backend/src/utils/enums.js
- backend/src/utils/parseSheet.js
- backend/tests/interview.test.js
- backend/yarn.lock
- frontend/package.json
- frontend/src/components/candidateBox.js
- frontend/src/components/candidateCard.js
- frontend/src/components/candidateStatus.js
- frontend/src/components/changeStatus.js
- frontend/src/components/facemashProfile.js
- frontend/src/components/interviewDetails.js
- frontend/src/pages/candidate.js
- frontend/src/pages/dashboard.js
- frontend/src/pages/interview.js
- frontend/src/pages/stats.js
- frontend/src/pages/table.js
- frontend/src/static/style.css
- frontend/src/utils/api.js
- frontend/src/utils/enums.js
- frontend/yarn.lock
Resolves #192 
Resolves #173 
Resolves #142 
Resolves #172 
A ton of stuff... sorry hehe
Also moved Change Status Dropdown to a separate component. upgraded next.js as well :)
> A ton of stuff

- backend/now.json
- backend/src/api/candidates.js
- backend/src/api/interview.js
- backend/src/models/candidate.js
- backend/src/models/index.js
- backend/src/models/interview.js
- backend/tests/candidates.test.js
- backend/tests/interview.test.js
- frontend/now.json
- frontend/src/components/addCommentsModal.js
- frontend/src/components/candidateInterviewsModal.js
- frontend/src/components/interviewDetails.js
- frontend/src/components/nav.js
- frontend/src/components/verificationModal.js
- frontend/src/pages/dashboard.js
- frontend/src/pages/interview.js
- frontend/src/pages/interviewportal.js
- frontend/src/pages/past-interviews.js
- frontend/src/pages/stats.js
- frontend/src/pages/table.js
- frontend/src/static/style.css
- frontend/src/utils/api.js
> Moves interviews into candidates and minor fixes throughout the app

- backend/package.json
- backend/src/api/futureInterview.js
- backend/src/api/index.js
- backend/src/models/futureInterview.js
- backend/src/models/index.js
- backend/src/routes.js
- frontend/src/utils/api.js
Resolves #218 
CSV schedule can be parsed according to a very specific format. I'll have a template available on the drive to make these schedules from. But the data can be consumed and stored in the database now, after being uploaded from the frontend.
> Schedule parser parse

- frontend/src/pages/interviewschedule.js
- frontend/src/static/style.css
- frontend/src/utils/api.js
Resolves #219:
The parser can now display interviews.
> Schedule parser display

- backend/src/api/candidates.js
- backend/src/models/candidate.js
- frontend/src/components/candidates/candidateBox.js
- frontend/src/pages/candidate.js
- frontend/src/utils/api.js
- frontend/yarn.lock
Resolves #213 
Adds two buttons to the bottom of candidate profile - refer and delete referral. Implemented logic for unique referral per user.
> Implement Basic Referrals

- backend/now.json
- frontend/src/utils/api.js
to be compatible with now version 2
> small update for deployments

- backend/src/api/candidates.js
- backend/src/models/candidate.js
- frontend/src/components/candidates/candidateBox.js
- frontend/src/pages/candidate.js
- frontend/src/utils/api.js
Resolves #214 
Implement strong referrals. Each user can only refer or strongly refer, not both.
> Implement strong referral (referral levels)

- backend/src/api/candidates.js
- backend/src/models/candidate.js
- backend/src/utils/enums.js
- backend/yarn.lock
- frontend/src/components/filterComponent.js
- frontend/src/pages/dashboard.js
- frontend/src/reducers/initialState.js
- frontend/src/static/style.css
- frontend/src/utils/enums.js
Resolves #225 and resolves #206 (EPIC)
Implement filtering in the Query Panel in the dashboard based on referral level
> Implement referral filter

- backend/now.json
- frontend/src/components/interviewSectionModular.js
- frontend/src/components/nav.js
- frontend/src/data/roundData.js
- frontend/src/pages/dashboard.js
- frontend/src/pages/interview.js
- frontend/src/pages/interviewschedule.js
- frontend/src/reducers/initialState.js
- frontend/src/utils/enums.js
also added emails as a select
and added /interview as a link when you click on a card in the interview schedule
> Finalized Interview 2nd Round Notes

- backend/src/api/candidates.js
- backend/src/api/interview.js
- backend/src/models/interview.js
- frontend/src/components/candidates/candidateBox.js
- frontend/src/components/interviewCard.js
- frontend/src/components/roundDropdown.js
- frontend/src/data/README.md
- frontend/src/data/roundData.js
- frontend/src/pages/_app.js
- frontend/src/pages/candidate.js
- frontend/src/pages/dashboard.js
- frontend/src/pages/facemash.js
- frontend/src/pages/index.js
- frontend/src/pages/interview.js
- frontend/src/pages/interviewlist.js
- frontend/src/pages/interviewportal.js
- frontend/src/pages/interviewschedule.js
- frontend/src/pages/rounds.js
- frontend/src/pages/stats.js
- frontend/src/pages/table.js
- frontend/src/utils/api.js
- frontend/src/utils/core.js
Resolves #240 
Also:
- fixed Navbar refresh problem (we had the navbar in `_app.js` so it didn't re-render.)
shows category in candidate page, if the `Category` section exists in the interview
shows the round in the interview modal
> Track interview round

- backend/now.json
- backend/src/api/interview.js
- frontend/now.json
- frontend/src/components/nav.js
- frontend/src/pages/analytics.js
- frontend/src/pages/index.js
- frontend/src/pages/interviewlist.js
- frontend/src/pages/interviewportal.js
- frontend/src/pages/login.js
- frontend/src/pages/stats.js
- frontend/src/utils/api.js
Resolves #243 
moving key store to localstorage allows you to create a new tab and still have your user logged in. Showing candidates in their respective categories given to them would help deliberations a lot in goign through candidates.
> Fixes #243 and moves key storage from sessionstorage to localstorage

- backend/package.json
- backend/yarn.lock
- frontend/src/components/interviewSectionModular.js
- frontend/src/pages/dashboard.js
- frontend/src/pages/interviewlist.js
- frontend/src/pages/stats.js
- frontend/src/utils/api.js
- frontend/yarn.lock
- Resolve security vulnerabilities in dependencies 
- Remove unused export `getAllCandidates` in [api.js](https://github.com/hack4impact-uiuc/h4i-recruitment/blob/master/frontend/src/utils/api.js)
> Resolve security vulnerabilities in dependencies

- backend/package.json
- backend/src/api/candidates.js
- backend/src/api/interview.js
- backend/src/index.js
- backend/yarn.lock
- frontend/src/components/candidates/candidateBox.js
- frontend/src/components/candidates/candidateInterviewsModal.js
- frontend/src/components/interviewCard.js
- frontend/src/pages/candidate.js
- frontend/src/pages/interviewlist.js
- frontend/yarn.lock
Resolves #242 
Also makes some minor changes to mongoose to get rid of warnings.
> Add the ability to delete interviews

- backend/package.json
- backend/tests/interview.test.js
- backend/tests/matches.test.js
> Fix backend tests timeout

- backend/package.json
- backend/tests/candidates.test.js
- backend/tests/getGithubContributions.test.js
- backend/tests/interview.test.js
- backend/tests/matches.test.js
- backend/tests/mongo_utils.js
- backend/tests/utils.js
Backend tests still failing. Resolves #267, resolves #266.
> Fix backend tests again

- backend/package.json
- backend/tests/candidates.test.js
- backend/tests/events.test.js
- backend/tests/interview.test.js
- backend/tests/matches.test.js
- backend/tests/mongo_utils.js
> Event backend tests

- backend/src/models/attendee.js
- backend/src/models/candidate.js
- backend/src/models/event.js
- backend/src/models/futureInterview.js
- backend/src/models/user.js
- backend/src/utils/populate.js
This is part of a larger change, where we plan to store the column as a required column and implement it in our database actions.
Resolves #275
> Workspace schema change

- backend/src/api/attendees.js
- backend/src/api/events.js
- backend/src/api/index.js
- backend/src/models/attendee.js
- backend/src/models/event.js
- backend/src/models/index.js
- backend/src/routes.js
> Attendee Backend

- backend/package.json
- backend/src/api/events.js
- backend/src/models/attendee.js
- backend/src/models/candidate.js
- backend/src/models/event.js
- backend/src/utils/utils.js
- backend/yarn.lock
> Event check-in backend

- frontend/src/components/comments/addCommentsModal.js
- frontend/src/components/comments/commentBox.js
- frontend/src/pages/candidate.js
- frontend/src/pages/login.js
- frontend/src/static/style.css
- frontend/src/utils/core.js
- comment input tracks newline and shows newlines
- readable date
- remove support for using "enter" to create a comment
- Login Modal goes to `/dashboard` since we don't really use facemash
Styling Changes
- comment box header color is changed to be lighter 
- `Show Candidate Interviews` button is changed to `Show Interviews`
- Horizontal bar added to provide separation all the other candidate information
> slight styling changes and comment improvements

- backend/src/api/cycle.js
- backend/src/models/cycle.js
- backend/tests/cycle.test.js
part of #249 
Using the workspace name instead of the chapter (which functionally represent the same thing)
> refactor chapter -> workspaceName

- backend/src/api/interview.js
- backend/src/models/index.js
- backend/src/models/workspace.js
- backend/tests/interview.test.js
- frontend/src/components/nav.js
Part of #280 
Director only nav items, and workspace model
The "workspaces" nav item is not available in leads or members nav bar
> Director only nav items, workspace schema

- backend/src/api/cycle.js
- backend/src/models/cycle.js
- backend/tests/cycle.test.js
- backend/tests/events.test.js
Add a `current` field to `Cycle`, which lets us know which Cycles are current and which ones are dated
> Current cycle

- frontend/src/pages/candidate.js
pr 302 broke candidates page, this fixes it
> fix broken candidates page

- frontend/src/components/eventsModal.js
- frontend/src/pages/eventOverview.js
- frontend/src/utils/formFields.js
> Create separate modal component for use on event pages

- backend/src/api/index.js
- backend/src/api/workspaces.js
- backend/src/models/workspace.js
- backend/src/routes.js
- backend/tests/artifacts/test-keys.json
- backend/tests/workspaces.test.js
Resolves #321
API layer for workspace requests
> Workspaces API Layer

- frontend/package.json
> Run prettier as part of a commit hook

- frontend/src/components/candidates/candidateBox.js
- frontend/src/components/candidates/candidateInterviewsModal.js
- frontend/src/components/interviewCard.js
- frontend/src/components/nav.js
- frontend/src/pages/candidate.js
- frontend/src/pages/interview.js
- frontend/src/pages/interviewlist.js
- frontend/src/pages/interviewportal.js
- frontend/src/static/style.css
- frontend/yarn.lock
- Interview Modals 
- added Exit button on top right
-  exit by clicking outside of modal
- Button color updates for more clarity in action
- Click the `Overall Interview score` to view details of interview
- made modals bigger
- nav bar
-  items reorganized around
-  Added `Your interviews` item because /interviewportal doesn't show up if Facemash is on
- Interview List Page
- Fix bug where it renders all of the interview modals for all the candidates
- Candidate Page
- Table format for interview information
- Move `Show Interview` Button to the right. Gives better ease of access, since the buttons below are getting pretty clustered. 
- Delete Refer button is made yellow 
--------------------------------------------------------------------------- …
> UI/UX Changes & bug fixes

- backend/Dockerfile-dev
- frontend/Dockerfile
> Use full Node Docker image

- backend/src/api/cycle.js
- backend/src/api/workspaces.js
- backend/src/middleware/auth.js
- backend/src/models/attendee.js
- backend/src/models/candidate.js
- backend/src/models/event.js
- backend/src/models/futureInterview.js
- backend/src/models/user.js
- backend/src/models/workspace.js
- backend/tests/cycle.test.js
- backend/tests/mongo_utils.js
- backend/tests/user.test.js
- backend/tests/workspaces.test.js
- frontend/src/components/workspaceModal.js
- frontend/src/pages/workspaces.js
- frontend/src/static/style.css
- frontend/src/utils/api.js
- frontend/src/utils/formFields.js
Resolves #305 
- Added the user to the authentication layer (`auth.js`), which now allows backend to get the caller of an endpoint from the frontend.
- With that, we add an extra layer of security to cycles and workspaces, so that callers of each endpoint can only access data related to the workspace that they belong in. 
- Also added some data integrity checks to the `Users` table so that we have unique identifiers for users.
- Modified users and workspaces such that the relationship between the two entities can be one to many.
- Added backend capability to add a user to a workspace.
> Workspace TODOs

- frontend/src/pages/index.js
- frontend/src/pages/register.js
- frontend/src/static/style.css
Google Auth is not working with the admin table, so we will temporarily disable it. 
This PR also includes updates to the UI for login/register pages.
> Remove Google auth for now and fix styling 

- backend/src/app.js
> Bump body parser size to 50MB

- frontend/src/utils/core.js
> Fix score data with non-valid round data entries

- .gitignore
- backend/README.md
- backend/package.json
- backend/recreate_db.sh
- docker-compose.yml
- frontend/README.md
Resolves #367 
- Added the db service to the `docker-compose.yml` file
- Removed all commands from ./recreate_db.sh except for `dotenv yarn populatedb`
- Removed unused backend .env variables
> Dockerize Mongo

- .github/ISSUE_TEMPLATE.md
- frontend/package.json
- frontend/yarn.lock
> Add issue template

- frontend/src/pages/index.js
- vercel.json
> Fix frontend routing

- backend/src/utils/enums.js
- backend/src/utils/parseSheet.js
- frontend/src/components/candidateDropdown.js
- frontend/src/components/candidates/candidateBox.js
- frontend/src/components/filterComponent.js
- frontend/src/data/roundData.js
- frontend/src/pages/candidate/[cid].js
- frontend/src/pages/dashboard.js
- frontend/src/pages/interview.js
- frontend/src/utils/enums.js
Adds in changes deployed but not committed from Fa20 recruitment cycle.
> Add uncommitted changes from Fa20 recruitment

- backend/src/utils/parseSheet.js
Updates the parser and candidate view to reflect changes in the Fa21 recruitment cycle.
> Add Fa21 form updates
